services:

  minio:
    image: minio/minio
    ports:
      - "9100:9100"
      - "9101:9101"
    environment:
      MINIO_ROOT_USER: ${AWS_KEY}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET}
      CONSOLE_DEV_MODE: on
    command: ["minio", "server", "/data", "--console-address", ":9101","--address", ":9100"]

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9100 minio minio1234 &&
      mc mb local/$(echo $AWS_BUCKET) || true
      "
    environment:
      AWS_BUCKET: ${AWS_BUCKET}
